# Generated by Django 4.1.3 on 2022-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.CharField(default='Second', max_length=200),
            preserve_default=False,
        ),
    ]
