# Generated by Django 4.1.3 on 2022-11-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='/media/images/blob', upload_to='images/'),
            preserve_default=False,
        ),
    ]
