# Generated by Django 4.1.1 on 2022-12-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('working_hours', models.JSONField(default=list)),
                ('duration', models.CharField(max_length=5)),
            ],
        ),
    ]
