# Generated by Django 4.1.3 on 2022-11-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_options_note_name_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
