# Generated by Django 4.1.3 on 2022-11-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date',
            new_name='bddate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='reg_date',
        ),
    ]
