# Generated by Django 4.1.3 on 2022-11-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
