# Generated by Django 4.1.3 on 2022-11-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
