# Generated by Django 4.1.3 on 2022-11-06 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0005_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=10)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('id', models.CharField(max_length=12)),
                ('blood_type', models.CharField(max_length=3)),
                ('marital_status', models.CharField(max_length=8)),
                ('contact_number', models.CharField(max_length=12)),
                ('emergency_contact_number', models.CharField(max_length=12)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
            managers=[
                ('objects', patients.models.AccountManager()),
            ],
        ),
    ]
