# Generated by Django 4.1.3 on 2022-12-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_appointment_appointment_unique_appointment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'date', 'time'), name='unique_appointment'),
        ),
    ]
