# Generated by Django 4.1.3 on 2022-12-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_remove_appointment_unique_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment',
        ),
    ]
