# Generated by Django 4.1.3 on 2022-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='date',
            new_name='bddate',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='doctor',
            name='duration',
            field=models.CharField(default='15', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.CharField(default='5000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.JSONField(default=list),
        ),
    ]
